### ISSUE TITLE
Block drops broken using 1.16.4-9.0.1-fabric

### ISSUE THREAD

**Issue by Danklor** [TelepathicGrunt/UltraAmplifiedDimension-Fabric#3]
I tried starting a new world using version 1.16.4-9.0.1-fabric plus only the minimum required libraries, but when breaking logs, dirt and many other blocks that should be hand breakable no items would drop. There was no crash or any errors in the logs.

MacOS 1.14.6
Java: 1.8.0_271 64-bit
MultiMC version: 0.6.11-1370
Fabric Loader 0.10.8
Fabric API 0.29.3+1.16
Autoconfig 3.3.1
Cardinal Components 2.7.10
Cloth Config 4.8.3

All config files removed / defaulted.

**Comment by TelepathicGrunt** [comment]
uhhhhhh time for a hotfix. idk what's going on

hang on lol

**Comment by TelepathicGrunt** [comment]
I just posted v9.0.2 on curseforge which should fix this bug. Thank you for reporting this!
https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-dimension-fabric/files/3165307

**Comment by Danklor** [comment]
Thanks for the quick fix!
