### ISSUE TITLE
Dimension data not being created when mod titled, "Fabric Seasons" is installed

### ISSUE THREAD

**Issue by coreytr** [TelepathicGrunt/UltraAmplifiedDimension-Fabric#5]
When Minecraft tries to run both of these mods at the same time, something in the Fabric Seasons mod prevents Ultra Amplified Dimension from being able to create its "ultra_amplified_dimension" folder in the associated world folder's "dimensions" folder. I have found no other issues with this mod and a plethora of other mods though, with this exception.

**Comment by TelepathicGrunt** [comment]
Can you explain more of what the issue is? Can you access the dimension at all in-game and does it function?

**Comment by TelepathicGrunt** [comment]
Log with both mods on: https://paste.ee/p/y7RWZ

Looks like this is related to this issue report. Some of my surfacebuilders for biomes uses ice and snow blocks so by Seasons adding a new property to it, it blows up those surfacebuilders which in turn, blows up the biomes, which then blows up the entire dimensions oof.
https://github.com/lucaargolo/fabric-seasons/issues/18

Keep watch on that issue report. Once they fix that, our mods should work together again.

**Comment by TelepathicGrunt** [comment]
Seasons has been updated to fix this issue! Try updating seasons and see if the issue is resolved
