### ISSUE TITLE
[QUESTION] Required on client and server?

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/UltraAmplifiedDimension-Fabric#6]
Is the mod required on both the client and the server? If no, are there any benefits to having it on both?
*I assume yes, but just wanna be sure.*

**Comment by TelepathicGrunt** [comment]
Yes this mod is required on both client and server as I introduce a few new blocks and several of the sky coloring based on height also needs my mod on the client. Hope this helps!
