### ISSUE TITLE
Blame reports

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/UltraAmplifiedDimension-Fabric#7]
https://paste.srnyx.xyz/hinelayale.yml

**Comment by TelepathicGrunt** [comment]
Can you please share your entire latest.log file? I suspect there’s a lot of info being lost with this snippet

**Comment by TelepathicGrunt** [comment]
nvm. What the heck why is the biome failing to parse but no other error appears? wack

**Comment by srnyx** [comment]
> Can you please share your entire latest.log file?

https://paste.srnyx.xyz/oyupamuxiw.yaml

**Comment by TelepathicGrunt** [comment]
Thank you for the report! Turns out some biomes weren't spawning due to a typo in my dimension's json file lmao. v9.2.0 out now should fix this!
